config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :donors
  mount Intro::Engine => "/intro" #brainstaq.com/intro/admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :follows
  resources :subscribers, only: [:create, :new, :index]
  root to: "home#index"
  
  resources :conversations do
    resources :messages
  end
  resources :donations
  resources :contact, only: [:create]
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {
    registrations: 'registrations',
    confirmations: 'confirmations'
  }
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :ideas, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :comments
    member do
      put 'like', to: "ideas#like"
      put 'unlike', to: "ideas#unlike"
    end
  end
  post '/tinymce_assets' => 'tinymce_assets#create'
  # post "follow/user" => "users#follow_user", as: :follow_user

  post '/users/:username/follow', to: "users#follow", as: "follow_user"
  post '/users/:username/unfollow', to: "users#unfollow", as: "unfollow_user"
  
  # get 'user/followers', to: "users#followers", as: "user_followers"
  # get 'user/followees', to: "users#followees", as: "user_followees"

  #get '/moon', to: 'application#moon', as: 'moon'
  #get '/sun', to: 'application#sun', as: 'sun'

  get 'pages/about'
  get 'pages/career'
  get 'pages/help'
  get 'pages/terms' 
  get 'pages/privacy'

  get 'search' => 'search#index'

  get 'profile/:username' => 'users#profile', as: :profile

  get '/dashboard' => 'users#index'



  # Routes for blog
  # match '/blog',        to: 'blog_posts#index', as: :blog_posts, via: :get
  # match '/blog/:title', to: 'blog_posts#show', as: :blog_post, via: :get

  resources :users, only: [:profile] do
    get :ideas
  end
  
  resources :users do
    member do
      get 'followings' => 'follows#following'
      get 'followers' => 'follows#follower'
    end
  end

  post 'paystack/receive_webhooks', to: 'paystack#webhook'

  namespace :api do
    namespace :v1 do
      resources :donors
      mount Intro::Engine => "/intro" #brainstaq.com/intro/admin
      mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
      resources :follows
      resources :subscribers, only: [:create, :new, :index]
      root to: "home#index"
  
      resources :conversations do
        resources :messages
      end
      resources :donations
      resources :contact, only: [:create]
      devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {
        registrations: 'registrations',
        confirmations: 'confirmations'
      }
      authenticate :user, lambda { |u| u.admin? } do
        mount Sidekiq::Web => '/sidekiq'
      end
      resources :ideas, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
        resources :comments
        member do
          put 'like', to: "ideas#like"
          put 'unlike', to: "ideas#unlike"
        end
      end
      post '/tinymce_assets' => 'tinymce_assets#create'
      # post "follow/user" => "users#follow_user", as: :follow_user

      post '/users/:username/follow', to: "users#follow", as: "follow_user"
      post '/users/:username/unfollow', to: "users#unfollow", as: "unfollow_user"
  
      # get 'user/followers', to: "users#followers", as: "user_followers"
      # get 'user/followees', to: "users#followees", as: "user_followees"

      #get '/moon', to: 'application#moon', as: 'moon'
      #get '/sun', to: 'application#sun', as: 'sun'

      get 'pages/about'
      get 'pages/career'
      get 'pages/help'
      get 'pages/terms' 
      get 'pages/privacy'

      get 'search' => 'search#index'

      get 'profile/:username' => 'users#profile', as: :profile

      get '/dashboard' => 'users#index'



      # Routes for blog
      # match '/blog',        to: 'blog_posts#index', as: :blog_posts, via: :get
      # match '/blog/:title', to: 'blog_posts#show', as: :blog_post, via: :get

      resources :users, only: [:profile] do
        get :ideas
      end
  
      resources :users do
        member do
          get 'followings' => 'follows#following'
          get 'followers' => 'follows#follower'
        end
      end

      post 'paystack/receive_webhooks', to: 'paystack#webhook'
    end
  end

end

app/models/donor.rb
class Donor < ApplicationRecord
  belongs_to :user
  has_many :donations

  default_scope { order(created_at: :desc)}
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show]

  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all
    # @donors = Donation.where(donor_id: !current_user.id)
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
  end

  # GET /donors/new
  def new
    @donor = Donor.new
  end

  # GET /donors/1/edit
  def edit
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donor_params
      params.require(:donor).permit(:name, :email, :user_id)
    end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_form.html.erb
<%= form_with(model: donor, local: true) do |form| %>
  <% if donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
        <% donor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<% content_for :title, "Share and Discover Disruptive Ideas" %>

<h1>Editing Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<% content_for :title, "Share and Discover Disruptive Ideas" %>

<!-- <header class="section-header mb-5" style="padding-top: 150px;">
  <h3 span class="text-primary">Donors</span></h3>
</header>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donors.each do |donor| %>
      <tr>
        <td><%= donor.donation.id %></td>
        <td><%= donor.email %></td>
        <td><%= donor.user_id %></td>
        <td><%= link_to 'Show', donor %></td>
        <td><%= link_to 'Edit', edit_donor_path(donor) %></td>
        <td><%= link_to 'Destroy', donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->

app/views/donors/new.html.erb
<% content_for :title, "Share and Discover Disruptive Ideas" %>

<h1>New Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<% content_for :title, "Share and Discover Disruptive Ideas" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @donor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @donor.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @donor.user_id %>
</p>

<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>