config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :donors
  mount Intro::Engine => "/intro" #brainstaq.com/intro/admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :follows
  resources :subscribers, only: [:create, :new, :index]
  root to: "home#index"
  
  resources :conversations do
    resources :messages
  end
  resources :donations
  resources :contact, only: [:create]
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {
    registrations: 'registrations',
    confirmations: 'confirmations'
  }
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :ideas, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :comments
    member do
      put 'like', to: "ideas#like"
      put 'unlike', to: "ideas#unlike"
    end
  end
  post '/tinymce_assets' => 'tinymce_assets#create'
  # post "follow/user" => "users#follow_user", as: :follow_user

  post '/users/:username/follow', to: "users#follow", as: "follow_user"
  post '/users/:username/unfollow', to: "users#unfollow", as: "unfollow_user"
  
  # get 'user/followers', to: "users#followers", as: "user_followers"
  # get 'user/followees', to: "users#followees", as: "user_followees"

  #get '/moon', to: 'application#moon', as: 'moon'
  #get '/sun', to: 'application#sun', as: 'sun'

  get 'pages/about'
  get 'pages/career'
  get 'pages/help'
  get 'pages/terms' 
  get 'pages/privacy'

  get 'search' => 'search#index'

  get 'profile/:username' => 'users#profile', as: :profile

  get '/dashboard' => 'users#index'



  # Routes for blog
  # match '/blog',        to: 'blog_posts#index', as: :blog_posts, via: :get
  # match '/blog/:title', to: 'blog_posts#show', as: :blog_post, via: :get

  resources :users, only: [:profile] do
    get :ideas
  end
  
  resources :users do
    member do
      get 'followings' => 'follows#following'
      get 'followers' => 'follows#follower'
    end
  end

  post 'paystack/receive_webhooks', to: 'paystack#webhook'

  namespace :api do
    namespace :v1 do
      resources :donors
      mount Intro::Engine => "/intro" #brainstaq.com/intro/admin
      mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
      resources :follows
      resources :subscribers, only: [:create, :new, :index]
      root to: "home#index"
  
      resources :conversations do
        resources :messages
      end
      resources :donations
      resources :contact, only: [:create]
      devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {
        registrations: 'registrations',
        confirmations: 'confirmations'
      }
      authenticate :user, lambda { |u| u.admin? } do
        mount Sidekiq::Web => '/sidekiq'
      end
      resources :ideas, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
        resources :comments
        member do
          put 'like', to: "ideas#like"
          put 'unlike', to: "ideas#unlike"
        end
      end
      post '/tinymce_assets' => 'tinymce_assets#create'
      # post "follow/user" => "users#follow_user", as: :follow_user

      post '/users/:username/follow', to: "users#follow", as: "follow_user"
      post '/users/:username/unfollow', to: "users#unfollow", as: "unfollow_user"
  
      # get 'user/followers', to: "users#followers", as: "user_followers"
      # get 'user/followees', to: "users#followees", as: "user_followees"

      #get '/moon', to: 'application#moon', as: 'moon'
      #get '/sun', to: 'application#sun', as: 'sun'

      get 'pages/about'
      get 'pages/career'
      get 'pages/help'
      get 'pages/terms' 
      get 'pages/privacy'

      get 'search' => 'search#index'

      get 'profile/:username' => 'users#profile', as: :profile

      get '/dashboard' => 'users#index'



      # Routes for blog
      # match '/blog',        to: 'blog_posts#index', as: :blog_posts, via: :get
      # match '/blog/:title', to: 'blog_posts#show', as: :blog_post, via: :get

      resources :users, only: [:profile] do
        get :ideas
      end
  
      resources :users do
        member do
          get 'followings' => 'follows#following'
          get 'followers' => 'follows#follower'
        end
      end

      post 'paystack/receive_webhooks', to: 'paystack#webhook'
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].blank?
      redirect_to root_path, alert: "Empty field!"
    elsif params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @ideas = Idea.joins(:idea).where(ideas: {title:    query})
      @users = User.joins(:user).where(users: {first_name:    query})
    else
      @ideas = Idea.where("title like ? or description like ?", "%#{params[:query]}%", "%#{params[:query]}%")
      @users = User.where("first_name like ? or last_name like ?", "%#{params[:query]}%", "%#{params[:query]}%")
    end
  end

  def check_ideas_exists
    if Idea.exists?(:title => self.title)
    end
  end

  def check_users_exists
    if User.exists?(:first_name => self.first_name)
    elsif User.exists?(:last_name => self.last_name)
    end
  end

  # def search  
  #   if params[:search].blank?  
  #     redirect_to(root_path, alert: "Empty field!") and return  
  #   else
  #     @parameter = params[:search].downcase
  #     @ideas = Idea.where("lower(title) LIKE ?", "%#{@parameter}%")
  #     @users = User.all.where("lower(first_name) LIKE ?", "%#{@parameter}%")
  #   end  
  # end 

  # @results = Car.joins(:store).search(params[:search]).order("stores.name DESC")
  
end
 

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<% content_for :title, "Search" %>

<header class="section-header mb-5" style="padding-top: 150px;">
  <h3>Search <span class="text-primary">Results</span></h3>
</header>

<div class="container">
  <div class="row ng-scope">
    <div class="col-md-12 col-md-pull-3">
      <% c = 0 %>
      
      <% @ideas.each do |idea| %>
          <section class="search-result-item">
            <a class="image-link" href="<%= idea_url(idea) %>">
              <% if idea.image.present? %>
                <%=image_tag idea.image_url(:thumb), class: "image", style: "width: 200px; height: 200px;" %>
              <% end %>
            </a>
            <div class="search-result-item-body">
              <div class="row">
                <div class="col-sm-9">
                  <h4 class="search-result-item-heading">
                    <%= link_to idea.title, idea, class: 'text-dark', style: "font-weight: bold;" %>
                  </h4>
                  <p class="info usr-cnt"><%= idea.category.name %></p>
                
                  <a class="text-dark description" href="<%= idea_url(idea) %>">
                    <%= truncate(sanitize(idea.description, tags: []), length: 200) %>
                  </a>
                </div>
                <div class="col-sm-3 text-align-center">
                  <p class="value3 mt-sm"></p>
                  <p class="value3 mt-sm"></p>
                  <p class="info text-muted mb-0"><span class="fa fa-filter text-primary mr-1"></span> 
                    <%= "#{idea.relevance_bar}%" %> Relevance
                  </p>
                  <p class="fs-mini info text-muted mb-0"><span class="fa fa-eye text-primary mr-1"></span> 
                    <%= pluralize(idea.impressionist_count, 'View') %>
                  </p>
                  <p class="fs-mini info text-muted mb-3"><span class="fa fa-heart text-primary mr-1"></span> 
                    <%= pluralize(idea.get_likes.size, 'Like') %>
                  </p>
                  <%= link_to 'View More', idea, class: 'btn btn-primary btn-info btn-sm' %>
                </div>
              </div>
            </div>
          </section>
          <% c = c + 1 %>
        <% end %>
      
      <% @users.each do |user| %>
          <section class="search-result-item">
            <a class="image-link" href="<%= profile_path(user.username, @user) %>">
              <% if user.image.url %>
                <%=image_tag (user.image_url), class: "image", style: "width: 200px; height: 210px;" %>
              <% else %>
                <%= image_tag 'avatar.png', class: "image", style: "width: 200px; height: 210px;" %>
              <% end %>
            </a>
            <div class="search-result-item-body">
              <div class="row">
                <div class="col-sm-9">
                  <h4 class="search-result-item-heading">
                    <%= link_to user.full_name, profile_path(user.username, @user), class: 'text-dark' %>
                  </h4>
                  <p class="info usr-cnt"><%= user.country %></p>
                  <p class="description"><%= user.bio %></p>
                </div>
                <div class="col-sm-3 text-align-center">
                  <p class="value3 mt-sm"></p>
                  <p class="fs-mini info text-muted mb-"><%= (user.ideas.count) %> Ideas Shared</p>
                  <%= link_to 'View More', profile_path(user.username, @user), class: 'btn btn-primary btn-info btn-sm' %>
                </div>
              </div>
            </div>
          </section>
          <% c = c + 1 %>
        <% end %>
        <p class="search-results-count" style="position: absolute; top: -50px;">Showing <%= pluralize(c, 'result') %> containing your search!</p>  
      </div>
    </div>
  </div>

  <style>
    body {
      margin-top:20px;
      background-color: #eee;
    }

    .search-result-categories>li>a {
      color: #b6b6b6;
      font-weight: 400
    }

    .search-result-categories>li>a:hover {
      background-color: #ddd;
      color: #555
    }

    .search-result-categories>li>a>.glyphicon {
      margin-right: 5px
    }

    .search-result-categories>li>a>.badge {
      float: right
    }

    .search-results-count {
      margin-top: 10px
    }

    .search-result-item {
      padding: 20px;
      margin-bottom: 10px;
      background-color: #fff;
      border-radius: 4px
    }

    .search-result-item:after,
    .search-result-item:before {
      content: " ";
      display: table
    }

    .search-result-item:after {
      clear: both
    }

    .search-result-item .image-link {
      display: block;
      overflow: hidden;
      border-top-left-radius: 4px;
      border-bottom-left-radius: 4px
    }

    @media (min-width:768px) {
      .search-result-item .image-link {
        display: inline-block;
        margin: -20px 0 -20px -20px;
        float: left;
        width: 200px;
      }
    }

    @media (max-width:767px) {
      .search-result-item .image-link {
        max-height: 200px
      }
      .search-results-count {
        position: absolute;
        top: -70px !important;
      }
      
    }

    .search-result-item .image {
      max-width: 100%
    }

    .search-result-item .info {
      margin-top: 2px;
      font-size: 12px;
      color: #999
    }

    .search-result-item .description {
      font-size: 13px
    }

    .search-result-item+.search-result-item {
      margin-top: 20px
    }

    @media (min-width:768px) {
      .search-result-item-body {
        margin-left: 200px
      }
    }

    .search-result-item-heading {
      font-weight: 400px;
      margin-top: 10px;
    }

    .search-result-item-heading>a {
      color: #555
    }

    @media (min-width:768px) {
      .search-result-item-heading {
        margin: 0;
      }
    }
</style>