config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :donors
  mount Intro::Engine => "/intro" #brainstaq.com/intro/admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :follows
  resources :subscribers, only: [:create, :new, :index]
  root to: "home#index"
  
  resources :conversations do
    resources :messages
  end
  resources :donations
  resources :contact, only: [:create]
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {
    registrations: 'registrations',
    confirmations: 'confirmations'
  }
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :ideas, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :comments
    member do
      put 'like', to: "ideas#like"
      put 'unlike', to: "ideas#unlike"
    end
  end
  post '/tinymce_assets' => 'tinymce_assets#create'
  # post "follow/user" => "users#follow_user", as: :follow_user

  post '/users/:username/follow', to: "users#follow", as: "follow_user"
  post '/users/:username/unfollow', to: "users#unfollow", as: "unfollow_user"
  
  # get 'user/followers', to: "users#followers", as: "user_followers"
  # get 'user/followees', to: "users#followees", as: "user_followees"

  #get '/moon', to: 'application#moon', as: 'moon'
  #get '/sun', to: 'application#sun', as: 'sun'

  get 'pages/about'
  get 'pages/career'
  get 'pages/help'
  get 'pages/terms' 
  get 'pages/privacy'

  get 'search' => 'search#index'

  get 'profile/:username' => 'users#profile', as: :profile

  get '/dashboard' => 'users#index'



  # Routes for blog
  # match '/blog',        to: 'blog_posts#index', as: :blog_posts, via: :get
  # match '/blog/:title', to: 'blog_posts#show', as: :blog_post, via: :get

  resources :users, only: [:profile] do
    get :ideas
  end
  
  resources :users do
    member do
      get 'followings' => 'follows#following'
      get 'followers' => 'follows#follower'
    end
  end

  post 'paystack/receive_webhooks', to: 'paystack#webhook'

  namespace :api do
    namespace :v1 do
      resources :donors
      mount Intro::Engine => "/intro" #brainstaq.com/intro/admin
      mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
      resources :follows
      resources :subscribers, only: [:create, :new, :index]
      root to: "home#index"
  
      resources :conversations do
        resources :messages
      end
      resources :donations
      resources :contact, only: [:create]
      devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {
        registrations: 'registrations',
        confirmations: 'confirmations'
      }
      authenticate :user, lambda { |u| u.admin? } do
        mount Sidekiq::Web => '/sidekiq'
      end
      resources :ideas, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
        resources :comments
        member do
          put 'like', to: "ideas#like"
          put 'unlike', to: "ideas#unlike"
        end
      end
      post '/tinymce_assets' => 'tinymce_assets#create'
      # post "follow/user" => "users#follow_user", as: :follow_user

      post '/users/:username/follow', to: "users#follow", as: "follow_user"
      post '/users/:username/unfollow', to: "users#unfollow", as: "unfollow_user"
  
      # get 'user/followers', to: "users#followers", as: "user_followers"
      # get 'user/followees', to: "users#followees", as: "user_followees"

      #get '/moon', to: 'application#moon', as: 'moon'
      #get '/sun', to: 'application#sun', as: 'sun'

      get 'pages/about'
      get 'pages/career'
      get 'pages/help'
      get 'pages/terms' 
      get 'pages/privacy'

      get 'search' => 'search#index'

      get 'profile/:username' => 'users#profile', as: :profile

      get '/dashboard' => 'users#index'



      # Routes for blog
      # match '/blog',        to: 'blog_posts#index', as: :blog_posts, via: :get
      # match '/blog/:title', to: 'blog_posts#show', as: :blog_post, via: :get

      resources :users, only: [:profile] do
        get :ideas
      end
  
      resources :users do
        member do
          get 'followings' => 'follows#following'
          get 'followers' => 'follows#follower'
        end
      end

      post 'paystack/receive_webhooks', to: 'paystack#webhook'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :session_hash]

  IDEAS_PER_PAGE = 3

  def active?
    status == "active"
  end

  def inactive
    status == "inactive"
  end
  
  
  def index
    @page = params.fetch(:page, 0).to_i 
    @next_page = @page + 1 unless Idea.count < 9
    @prev_page = @page - 1 unless @page == 0
    @ideas = Idea.all.offset(@page*IDEAS_PER_PAGE).limit(IDEAS_PER_PAGE).sort_by { |idea| idea.impressions.size.to_i}.reverse
    
    @users = User.all
  end

  def impressionist_count
    impressions.size
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :title, "Share and Discover Disruptive Ideas" %>


<!--==========================
    Intro Section
============================-->
<section id="intro" class="clearfix">
  <div class="container d-flex h-100">
    <div class="row justify-content-center align-self-center">
      <div class="col-md-6 intro-info order-md-first order-last">
        <h2 style="margin-top: 200px;">Bring your ideas to life with <span> Brainstaq!</span></h2>
        <div>
      		<%= link_to 'Get Started', new_idea_path, class: "btn-get-started" %>
        </div>
      </div>
      
      <div class="col-lg-4 ml-auto form-box" data-aos="fade-up" data-aos-delay="500" style="margin-top: 180px; margin-bottom: 100px;">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <small><%= render "devise/shared/error_messages", resource: resource %></small>
          
          <h5 class="text-center" style="font-size: 16px;">Discover Disruptive Ideas<br>
            <span class="text-black" style="font-weight: bold; font-size: 22px;" > Join Now!</span>
          </h5>
          
          <div class="form-group">
            <%= f.text_field :last_name, required: true, class: "form-control", placeholder: "Last Name" %>
          </div>
          
          <div class="form-group">
            <%= f.text_field :first_name, required: true, class: "form-control", placeholder: "First Name" %>
          </div>

          <div class="form-group">
            <%= f.text_field :username, required: true, class: "form-control", placeholder: "Username" %>
          </div>

          <div class="form-group">
            <%= f.select :country, options_for_select([
            # ['Algeria'],
            # ['Angola'],
            # ['Benin'],
            # ['Botswana'],
            # ['Burkina Faso'],
            # ['Burundi'],
            # ['Cape Verde'],
            # ['Cameroon'],
            # ['Central African Republic (CAR)'],
            # ['Chad'],
            # ['Comoros'],
            # ['Republic of the Congo'],
            # ['Democratic Republic of Congo'],
            # ["Cote d'Ivoire"],
            # ['Djibouti'],
            # ['Egypt'],
            # ['Equatorial Guinea'],
            # ['Eritrea'],
            # ['Eswatini'],
            # ['Ethiopia'],
            # ['Gabon'],
            # ['Gambia'],
            # ['Ghana'],
            # ['Guinea'],
            # ['Guinea-Bissau'],
            # ['Kenya'],
            # ['Lesotho'],
            # ['Liberia'],
            # ['Libya'],
            # ['Madagascar'],
            # ['Malawi'],
            # ['Mali'],
            # ['Mauritania'],
            # ['Mauritius'],
            # ['Morocco'],
            # ['Mozambique'],
            # ['Namibia'],
            # ['Niger'],
            ['Nigeria']
            # ['Rwanda'],
            # ['Sao Tome and Principe'],
            # ['Senegal'],
            # ['Seychelles'],
            # ['Sierra Leone'],
            # ['Somalia'],
            # ['South Africa'],
            # ['South Sudan'],
            # ['Sudan'],
            # ['Tanzania'],
            # ['Togo'],
            # ['Tunisia'],
            # ['Uganda'],
            # ['Zambia'],
            # ['Zimbabwe']
            ]), {}, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.email_field :email, required: true, class: "form-control", placeholder: "Email Address" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
          </div>

          <div class="form-group mb-2">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Repeat Password" %>
          </div>
          
          <small>By signing up, you agree to Brainstaq's 
            <%= link_to 'Terms of Service', 'pages/terms', class: 'para-font' %> and
            <%= link_to 'Privacy Policy', 'pages/privacy', class: 'para-font' %> 
          </small>

          <div class="field captcha mt-2 form-group">
            <%= recaptcha_tags %>
          </div>
          
          <div class="form-group"  style="margin-top: 10px; margin-bottom: 0px">
            <%= f.submit "Create Account", class: "btn btn1 btn-block text-white" %>
          </div>
        <% end %>
      </div><!-- col end-->
    </div><!-- row end-->
  </div><!-- container end-->
</section><!-- #intro -->

<!--==========================
  Trending Ideas Section
============================-->
<main id="main">
  <section id="why-us" class="mb-0">
    <div class="container-fluid">  
      <header class="section-header mt-3">
        <h3>Trending<span class="text-primary"> Ideas</span></h3>
        <p style="font-size: 18px;">We celebrate innovative ideas and projects with the 
          potential to disrupt ecosystems in Africa
        </p>
      </header>
    </div>
     
    <%= render partial: "layouts/ideas", locals: { ideas: @ideas} %>
    
    <div class="row justify-content-center mt-5">
      <div class="col-7 text-center"> 
        <% if @page > 0 %>
          <%= link_to 'Prev', root_path(page: @page - 1), class: "btn btn1 rounded-pill text-white mr-1" %>
        <% end %>
        <% if @ideas.count >= 3 %>
          <%= link_to 'Next', root_path(page: @page + 1), class: "btn btn1 rounded-pill text-white ml-1" %>
        <% end %>
      </div>
    </div>
  </section>
  <%= render partial: "layouts/counter" %>
  <%= render partial: "layouts/cta" %>

  <!--==========================
    Features Section
  ============================-->
  <section id="features">
    <div class="container">
      <div class="row feature-item">
        <div class="col-lg-6 wow fadeInUp">
          <%= image_tag 'features-1.svg', class: "img-fluid" %>
        </div>
        <div class="col-lg-6 wow fadeInUp pt-5 pt-lg-0">
          <h4>Are you an entrepreneur?<br>
            Seize the opportunities Brainstaq present!</h4>
          <p>
            Without adequate finances and funding, most of the ideas that can 
            change the African narrative are rarely able to break out from 
            being just an idea, let alone grow into a tangible business.
          </p>
          <p>
            Share your ideas, creations or insights with the public, get adequate exposure 
            and positive validations, get collaborators and raise the required funds to 
            make that idea a reality.
          </p>
          <p>
            Don’t watch that idea, project, or business disappear due to lack of funds. 
            Brainstaq will help you develop that business idea and build the resilience 
            needed to sustain your business over a period of time.
          </p>
        </div>
      </div>

      <div class="row feature-item mt-5 pt-5">
        <div class="col-lg-6 wow fadeInUp order-1 order-lg-2">
          <%= image_tag 'features-2.svg', class: "img-fluid" %>
        </div>

        <div class="col-lg-6 wow fadeInUp pt-4 pt-lg-0 order-2 order-lg-1">
          <h4>It goes beyond sharing of ideas.<br>
            Brainstaq empowers disruptive African ideas!
          </h4>
          <p>
            We are on a mission to help empower creative and innovative 
            ideas and encourage development among African startups and small businesses.
          </p>
          <p>
            We believe every African entrepreneur should have the tools to create the 
            solutions of tomorrow. And Brainstaq is dedicated to make this happen! 
          </p>
          <p>
            With our user-friendly, ideas-sharing and crowdfunding platform, 
            African entrepreneurs can start, nurture and grow their desired businesses 
            sustainably. 
          </p>
        </div>  
      </div>
    </div>
  </section>
  
  <%= render partial: "layouts/faq" %>
  
</main>