config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :donors
  mount Intro::Engine => "/intro" #brainstaq.com/intro/admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :follows
  resources :subscribers, only: [:create, :new, :index]
  root to: "home#index"
  
  resources :conversations do
    resources :messages
  end
  resources :donations
  resources :contact, only: [:create]
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {
    registrations: 'registrations',
    confirmations: 'confirmations'
  }
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :ideas, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :comments
    member do
      put 'like', to: "ideas#like"
      put 'unlike', to: "ideas#unlike"
    end
  end
  post '/tinymce_assets' => 'tinymce_assets#create'
  # post "follow/user" => "users#follow_user", as: :follow_user

  post '/users/:username/follow', to: "users#follow", as: "follow_user"
  post '/users/:username/unfollow', to: "users#unfollow", as: "unfollow_user"
  
  # get 'user/followers', to: "users#followers", as: "user_followers"
  # get 'user/followees', to: "users#followees", as: "user_followees"

  #get '/moon', to: 'application#moon', as: 'moon'
  #get '/sun', to: 'application#sun', as: 'sun'

  get 'pages/about'
  get 'pages/career'
  get 'pages/help'
  get 'pages/terms' 
  get 'pages/privacy'

  get 'search' => 'search#index'

  get 'profile/:username' => 'users#profile', as: :profile

  get '/dashboard' => 'users#index'



  # Routes for blog
  # match '/blog',        to: 'blog_posts#index', as: :blog_posts, via: :get
  # match '/blog/:title', to: 'blog_posts#show', as: :blog_post, via: :get

  resources :users, only: [:profile] do
    get :ideas
  end
  
  resources :users do
    member do
      get 'followings' => 'follows#following'
      get 'followers' => 'follows#follower'
    end
  end

  post 'paystack/receive_webhooks', to: 'paystack#webhook'

  namespace :api do
    namespace :v1 do
      resources :donors
      mount Intro::Engine => "/intro" #brainstaq.com/intro/admin
      mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
      resources :follows
      resources :subscribers, only: [:create, :new, :index]
      root to: "home#index"
  
      resources :conversations do
        resources :messages
      end
      resources :donations
      resources :contact, only: [:create]
      devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => {
        registrations: 'registrations',
        confirmations: 'confirmations'
      }
      authenticate :user, lambda { |u| u.admin? } do
        mount Sidekiq::Web => '/sidekiq'
      end
      resources :ideas, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
        resources :comments
        member do
          put 'like', to: "ideas#like"
          put 'unlike', to: "ideas#unlike"
        end
      end
      post '/tinymce_assets' => 'tinymce_assets#create'
      # post "follow/user" => "users#follow_user", as: :follow_user

      post '/users/:username/follow', to: "users#follow", as: "follow_user"
      post '/users/:username/unfollow', to: "users#unfollow", as: "unfollow_user"
  
      # get 'user/followers', to: "users#followers", as: "user_followers"
      # get 'user/followees', to: "users#followees", as: "user_followees"

      #get '/moon', to: 'application#moon', as: 'moon'
      #get '/sun', to: 'application#sun', as: 'sun'

      get 'pages/about'
      get 'pages/career'
      get 'pages/help'
      get 'pages/terms' 
      get 'pages/privacy'

      get 'search' => 'search#index'

      get 'profile/:username' => 'users#profile', as: :profile

      get '/dashboard' => 'users#index'



      # Routes for blog
      # match '/blog',        to: 'blog_posts#index', as: :blog_posts, via: :get
      # match '/blog/:title', to: 'blog_posts#show', as: :blog_post, via: :get

      resources :users, only: [:profile] do
        get :ideas
      end
  
      resources :users do
        member do
          get 'followings' => 'follows#following'
          get 'followers' => 'follows#follower'
        end
      end

      post 'paystack/receive_webhooks', to: 'paystack#webhook'
    end
  end

end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user, foreign_key: :donor_id, class_name: "User"
  belongs_to :idea
  belongs_to :perk, optional: true

  default_scope { order(created_at: :desc)}
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, :authenticate_user!

  def index
    @donations = Donation.where(idea_id: current_user.ideas)
    #@ideas = @user.ideas_with_donations
    #@donation.idea_id = @idea.id
  end
  
  def new
    @idea = current_user.ideas.build
    @idea = Idea.find_by_id params[:idea]
  end

  def create
    @donor_id = params[:donor_id]
    @email = params[:email]
    @idea_id = params[:idea_id]
    # @perk_id = params[:perk_id]
    @amount = params[:amount]
    @donation = current_user.donations.build(
      :amount => @amount,
      :donor_id => @donor_id,
      :idea_id => @idea_id,
      # :perk_id => @perk_id,
      # :response_reference => @response_reference
      )
    @donor_id = current_user.id
    @idea_id = Idea.find_by_id params[:idea]
    # @perk = Perk.find_by_id params[:perk_id]
    if @donation.save!
      render json: { success: true}
    end
  end

  def show
    # # donation = Donation.find(params[:id])
    # @donation = Donation.where(idea_id: current_user.ideas)
    # render :show
  end

  def donor
    # @donor ||= Donation.find_by(user: donor_id, idea: idea_id)
  end
  
  private

  def donation_params
    params.permit(:idea_id, :donor_id, :response_reference, :amount, :email, :phone)
  end

  def donations
    params.permit(:idea_id, :donor_id, :response_reference, :amount)
  end
end

app/views/donations/_form.html copy.erb
<div>
  <form id="pay-form">
    <input type="hidden" id="idea" name="idea" value="<%= params[:idea] %>">
    <input type="hidden" id="perk" name="perk" value="<%= params[:perk] %>">
    <input type="hidden" id="amount" name="amount" value="<%= params[:amount] %>">
    <input type="hidden" id="email" name="email" value="<%= current_user.email %>">
    <input type="hidden" id="phone" name="phone" value="<%= current_user.phone %>">
    <input type="hidden" id="fullname" name="fullname" value="<%= current_user.full_name %>">
    <p>
      <button class="btn btn1 text-white" type="submit" id="submit" onclick="payWithPaystack()"> 
        Donate <%= number_to_currency(params[:amount], :unit => "N") %>
      </button>
    </p>
  </form>
</div>
<script src="https://js.paystack.co/v1/inline.js"></script>
<script>
  var public_key = 'pk_test_dbc69abc1c9ab93762b8fa610c3628dda0231e3c';

  const email = document.getElementById('email').value;
  const amount = 100 * +document.getElementById('amount').value;
  const fullname = document.getElementById('fullname').value;
  const phone  = document.getElementById('phone').value;
    
  payWithPaystack(email, amount, fullname, phone);

  function generateREF(){
    var d = new Date().getTime();
    if(window.performance && typeof window.performance.now === "function"){
      d += performance.now();
    }
    var ref = '<%= params[:idea] %>-xxxx-4xxx-<%= params[:perk] %>-xxxx'.replace(/[xy]/g, function(c) {
      var r = (d + Math.random()*16)%16 | 0;
      d = Math.floor(d/16);
      return (c=='x' ? r : (r&0x3|0x8)).toString(16);
    });
    return ref;
  }
  
  function payWithPaystack(email, amount, fullname, phone){
    var handler = PaystackPop.setup({
      key:       public_key,
      email:     email,
      fullname:  fullname,
      phone:     phone,
      amount:    amount,
      ref:       generateREF(),
      // metadata: {
      //    custom_fields: [
      //       {
      //           display_name: "donation id",
      //           variable_name: "donation_id",
      //           value: @donation.id
      //       }
      //    ]
      // },
      callback: function(response){
        var msg = 'Donation Successful! Transaction Reference: <b>"' + response.trxref + '"</b>';
        document.getElementById('alert-holder').innerHTML = '<div class="alert alert-success m-2 text-center">' + msg + '</div>';
        //document.getElementById("pay-form").reset();
      },
      
      onClose:  function(){
        var msg = 'Cancelled! Please click the \'Donate\' button to try again';
        document.getElementById('alert-holder').innerHTML = '<div class="alert alert-danger text-center">' + msg + '</div>';
      }
    });
    handler.openIframe();
  }
</script>
 

app/views/donations/_form.html.erb
<!-- <div>
  <form id="pay-form">
    <input type="hidden" id="donor_id" name="donor_id" value="<%= current_user.id %>">
    <input type="hidden" id="idea_id" name="idea_id" value="<%= @idea.id %>">
    <input type="hidden" id="perk_id" name="perk_id" value="<%= params[:perk] %>">
    <input type="hidden" id="amount" name="amount" value="<%= params[:amount] %>">
    <input type="hidden" id="email" name="email" value="<%= current_user.email %>">
    <input type="hidden" id="phone" name="phone" value="<%= current_user.phone %>">
    <input type="hidden" id="fullname" name="fullname" value="<%= current_user.full_name %>">
    <p>
      <button class="btn btn1 text-white" type="submit" id="submit" onclick="payWithPaystack()"> 
        Donate <%= number_to_currency(params[:amount], :unit => "N") %>
      </button>
    </p>
  </form>
</div>
<script src="https://js.paystack.co/v1/inline.js"></script>
<script>
  var public_key = 'pk_test_dbc69abc1c9ab93762b8fa610c3628dda0231e3c';

  const email = document.getElementById('email').value;
  const amount = 100 * +document.getElementById('amount').value;
  const fullname = document.getElementById('fullname').value;
  const phone  = document.getElementById('phone').value;
  const donor_id  = document.getElementById('donor_id').value;
  const idea_id  = document.getElementById('idea_id').value;
  const perk_id  = document.getElementById('perk_id').value;
    
  payWithPaystack(email, amount, fullname, phone);

  function generateREF(){
    var d = new Date().getTime();
    if(window.performance && typeof window.performance.now === "function"){
      d += performance.now();
    }
    var ref = '<%= params[:idea] %>-xxxx-4xxx-<%= params[:perk] %>-xxxx'.replace(/[xy]/g, function(c) {
      var r = (d + Math.random()*16)%16 | 0;
      d = Math.floor(d/16);
      return (c=='x' ? r : (r&0x3|0x8)).toString(16);
    });
    return ref;
  }
  
  function payWithPaystack(email, amount, fullname, phone){
    // var response_reference = undefined
    var handler = PaystackPop.setup({
      key:       public_key,
      email:     email,
      fullname:  fullname,
      phone:     phone,
      amount:    amount,
      ref:       generateREF(),
      // metadata:{
      //   donor_id: donor.id,
      //   idea_id: idea.id,
      //   perk_id: perk.id,
      //   amount: amount
      // },
      callback: function(response){
        var msg = 'Donation Successful! Transaction Reference: <b>"' + response.trxref + '"</b>';
        document.getElementById('alert-holder').innerHTML = '<div class="alert alert-success m-2 text-center">' + msg + '</div>';
        //document.getElementById("pay-form").reset();
      },
      
      onClose:  function(){
        var msg = 'Cancelled! Please click the \'Donate\' button to try again';
        document.getElementById('alert-holder').innerHTML = '<div class="alert alert-danger text-center">' + msg + '</div>';
      }
    });
    handler.openIframe();
  }
</script>
  -->


  <div>
    <form id="pay-form">
      <input type="hidden" id="donor_id" name="donor_id" value="<%= current_user.id %>">
    <input type="hidden" id="idea_id" name="idea_id" value="<%= @idea.id %>">
    <input type="hidden" id="perk_id" name="perk_id" value="<%= params[:perk] %>">
      <input type="hidden" id="idea" name="idea" value="<%= params[:idea] %>">
      <input type="hidden" id="perk" name="perk" value="<%= params[:perk] %>">
      <input type="hidden" id="amount" name="amount" value="<%= params[:amount] %>">
      <input type="hidden" id="email" name="email" value="<%= current_user.email %>">
      <input type="hidden" id="phone" name="phone" value="<%= current_user.phone %>">
      <input type="hidden" id="fullname" name="fullname" value="<%= current_user.full_name %>">
      <p>
        <button class="btn btn1 text-white" type="submit" id="submit" onclick="payWithPaystack()"> 
          Donate <%= number_to_currency(params[:amount], :unit => "₦") %>
        </button>
      </p>
    </form>
  </div>
  <script src="https://js.paystack.co/v1/inline.js"></script>
  <script>
    var public_key = 'pk_live_8bd5b07c673470ce971c9311fb8662243608e0d1';
    var response_reference = undefined
  
    const email = document.getElementById('email').value;
    const amount = 100 * +document.getElementById('amount').value;
    const fullname = document.getElementById('fullname').value;
    const phone  = document.getElementById('phone').value;
    const donor_id = document.getElementById('donor_id').value;
    const idea_id = document.getElementById('idea_id').value;
    const perk_id = document.getElementById('perk_id').value;
      
    payWithPaystack(email, amount, donor_id, idea_id, perk_id, response_reference, phone);
  
    function generateREF(){
      var d = new Date().getTime();
      if(window.performance && typeof window.performance.now === "function"){
        d += performance.now();
      }
      var response_reference = '<%= params[:idea] %>-xxxx-4xxx-<%= params[:perk] %>-xxxx'.replace(/[xy]/g, function(c) {
        var r = (d + Math.random()*16)%16 | 0;
        d = Math.floor(d/16);
        return (c=='x' ? r : (r&0x3|0x8)).toString(16);
      });
      return response_reference;
    }
    
    function payWithPaystack(email, amount, donor_id, idea_id, perk_id, response_reference, phone){
      var response_reference = undefined
      var handler = PaystackPop.setup({
        key:       public_key,
        email:     email,
        donor_id: donor_id,
        idea_id: idea_id,
        perk_id: perk_id,
        phone:     phone,
        amount:    amount,
        response_reference: generateREF(),
        metadata: {
          donor_id: donor_id,
          idea_id: idea_id,
          perk_id: perk_id,
          amount: amount,
          response_reference: generateREF()
        },
        callback: function(response){
          var response_reference = undefined
  
          const email = document.getElementById('email').value;
          const amount = 100 * +document.getElementById('amount').value;
          const fullname = document.getElementById('fullname').value;
          const phone  = document.getElementById('phone').value;
          const donor_id = document.getElementById('donor_id').value;
          const idea_id = document.getElementById('idea_id').value;
          const perk_id = document.getElementById('perk_id').value;
          
          $.ajax({
              url:'/donations',
              type:'POST',
              dataType:'json',
              data:{
                response_reference: response_reference,
                email:     email,
                donor_id: donor_id,
                idea_id: idea_id,
                perk_id: perk_id,
                phone:     phone,
                amount:    amount,
                authenticity_token: window._token
              },
              success:function(data){
                console.log(data.success)
                console.log(data.user_fullname)
                console.log(data.result)
                $('.loader_image').hide()
                $('.success_msg').show();
                // $('#overlay').hide()
                $('.namer').text(data.user_fullname)
              },
              error:function(data){
                console.log(data)
                 $('.loader_image').hide();
                 // $('#overlay').hide()

              }
            });

          var msg = 'Donation Successful! Transaction Reference: <b>"' + response.trxref + '"</b>';
          document.getElementById('alert-holder').innerHTML = '<div class="alert alert-success m-2 text-center">' + msg + '</div>';
          //document.getElementById("pay-form").reset();
        },
        
        onClose:  function(){
          var msg = 'Cancelled! Please click the \'Donate\' button to try again';
          document.getElementById('alert-holder').innerHTML = '<div class="alert alert-danger text-center">' + msg + '</div>';
        }
      });
      handler.openIframe();
    }
  </script>

app/views/donations/_form.html_copy.erb
<div>
  <form id="pay-form">
    <input type="hidden" id="idea" name="idea" value="<%= params[:idea] %>">
    <input type="hidden" id="perk" name="perk" value="<%= params[:perk] %>">
    <input type="hidden" id="amount" name="amount" value="<%= params[:amount] %>">
    <input type="hidden" id="email" name="email" value="<%= current_user.email %>">
    <input type="hidden" id="phone" name="phone" value="<%= current_user.phone %>">
    <input type="hidden" id="fullname" name="fullname" value="<%= current_user.full_name %>">
    <p>
      <button class="btn btn1 text-white" type="submit" id="submit" onClick="makePayment()"> 
        Donate <%= number_to_currency(params[:amount], :unit => "N") %>
      </button>
    </p>
  </form>
</div>
<script src="https://checkout.flutterwave.com/v3.js"></script>
<script>
  var public_key = "FLWPUBK_TEST-07496b219a30824e8c250b91e64f8c84-X";

  const email = document.getElementById('email').value;
  const amount = 100 * +document.getElementById('amount').value;
  const fullname = document.getElementById('fullname').value;
  const phone  = document.getElementById('phone').value;
    
  makePayment(email, amount, fullname, phone);

  function generateREF(){
    var d = new Date().getTime();
    if(window.performance && typeof window.performance.now === "function"){
      d += performance.now();
    }
    var tx_ref = '<%= params[:idea] %>-xxxx-4xxx-<%= params[:perk] %>-xxxx'.replace(/[xy]/g, function(c) {
      var r = (d + Math.random()*16)%16 | 0;
      d = Math.floor(d/16);
      return (c=='x' ? r : (r&0x3|0x8)).toString(16);
    });
    return tx_ref;
  }
  
  function makePayment(email, amount, fullname, phone){
    FlutterwaveCheckout({
      key:       public_key,
      email:     email,
      fullname:  fullname,
      phone:     phone,
      amount:    amount,
      tx_ref:    generateREF(),
      
      callback: function(response){
        var msg = 'Donation Successful! Transaction Reference: <b>"' + response.trxref + '"</b>';
        document.getElementById('alert-holder').innerHTML = '<div class="alert alert-success m-2 text-center">' + msg + '</div>';
        //document.getElementById("pay-form").reset();
      },
      
      onClose:  function(){
        var msg = 'Cancelled! Please click the \'Donate\' button to try again';
        document.getElementById('alert-holder').innerHTML = '<div class="alert alert-danger text-center">' + msg + '</div>';
      }
    });
    handler.openIframe();
  }
</script>

app/views/donations/index.html.erb
<% content_for :title, "Share and Discover Disruptive Ideas" %>

<header class="section-header mb-5" style="padding-top: 150px;">
  <h3 span class="text-primary">Donations</span></h3>
</header>

<div class="container-fluid mb-5" style="width: 1000px" class="mx-auto">
  <div class="container">
    <div class="row py-5">
      <div class="col-12">
        <table id="example" class="table table-hover responsive nowrap" style="width:100%">
          <thead>
            <tr>
              <th>ID</th>
              <th>Donor</th>
              <th>Amount</th>
              <th>Date</th>
              <th>Idea</th>
            </tr>
          </thead>
          <tbody>
          <% @donations.each do |donation| %>
            <tr>
              <td><%= donation.id %></td>
              <td>
                <div class="d-flex align-items-center">
                  <div class="mr-3"><%= image_tag donation.user.image_url, style:"width:28px; height: 28px; margin-right: 0px;", class: "rounded-circle" %></div>
                  <div class="">
                    <p class="font-weight-bold mb-0"><%= link_to (donation.user.full_name), profile_path(donation.user.username) %></p>
                    <p class="text-muted mb-0"><%= donation.user.email %></p>
                  </div>
                </div>
              </td>
              <td><%= number_to_currency(donation.amount/100, :unit => "₦") %></td>
              <td><%= donation.created_at.strftime("%d/%m/%Y") %></td>
              <td><%= link_to (donation.idea.title), idea_path(donation.idea) %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

<style>
  /* body {
  background: #f7f7f7;
} */

.table {
  border-spacing: 0 0.85rem !important;
}

.table td,
.table th {
  vertical-align: middle;
  margin-bottom: 10px;
  border: none;
}

.table thead tr,
.table thead th {
  border: none;
  font-size: 18px;
  font-weight: bold;
  letter-spacing: 1px;
  text-transform: uppercase;
  background: transparent;
}

.table td:first-child {
  border-top-left-radius: 10px;
  border-bottom-left-radius: 10px;
}

.table td:last-child {
  border-top-right-radius: 10px;
  border-bottom-right-radius: 10px;
}

table.dataTable.dtr-inline.collapsed
  > tbody
  > tr[role="row"]
  > td:first-child:before,
table.dataTable.dtr-inline.collapsed
  > tbody
  > tr[role="row"]
  > th:first-child:before {
  top: 28px;
  left: 14px;
  border: none;
  box-shadow: none;
}

table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > td:first-child,
table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > th:first-child {
  padding-left: 48px;
}

table.dataTable > tbody > tr.child ul.dtr-details {
  width: 100%;
}

table.dataTable > tbody > tr.child span.dtr-title {
  min-width: 50%;
}

table.dataTable.dtr-inline.collapsed > tbody > tr > td.child,
table.dataTable.dtr-inline.collapsed > tbody > tr > th.child,
table.dataTable.dtr-inline.collapsed > tbody > tr > td.dataTables_empty {
  padding: 0.75rem 1rem 0.125rem;
}

div.dataTables_wrapper div.dataTables_length label,
div.dataTables_wrapper div.dataTables_filter label {
  margin-bottom: 0;
}

@media (max-width: 767px) {
  div.dataTables_wrapper div.dataTables_paginate ul.pagination {
    -ms-flex-pack: center !important;
    justify-content: center !important;
    margin-top: 1rem;
  }
}

.table a {
  color: #212529;
}

.table a:hover,
.table a:focus {
  text-decoration: none;
}

table.dataTable {
  margin-top: 12px !important;
}

/* .avatar-blue {
  background-color: #c8d9f1;
  color: #467fcf;
} */
</style>

app/views/donations/new.html.erb
<% content_for :title, "Donate" %>

<article class="card-body col-lg-12 mx-auto" style="max-width: 50%; padding-top: 150px;">
  <div class="section-header mb-5">
    <div id="alert-holder"></div>
    <h4 class="mb-2 text-center">You're about to support <br>
      <span class="text-primary">
        <%= link_to @idea.title, @idea %> 
      </span>
       Campaign 🎉</h4>
  </div>
  

  <% if user_signed_in? %>
    <div class="text-center">
      <%= render "form", idea: @idea %>
    </div>
  <% else %>
    <div class="p-6 text-center">
      <%= link_to "Sign in to support this idea", new_user_session_path, class: "btn btn1 text-white" %>
    </div>
  <% end %>
</article>

app/views/donations/show.html.erb
<% content_for :title, "Share and Discover Disruptive Ideas" %>